name: Ticket Tracker CI

on:
  push:
    branches: [ main, develop, add-github-actions ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test with Maven
        run: mvn clean verify

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: "**/target/surefire-reports/*.xml"